# CraftedGear Configuration File
# -----------------------------

# Debug Mode:
# true로 설정하면 플러그인의 추가적인 디버그 메시지가 콘솔에 출력됩니다.
# 개발 및 문제 해결 시 유용하며, 운영 중에는 false로 설정하는 것이 좋습니다.
debug_mode: false

# Resource Pack Settings:
# CraftedGear 커스텀 아이템의 모델과 텍스처를 표시하기 위한 리소스팩 설정입니다.
# ------------------------
# resource_pack_url:
#   플레이어가 서버에 접속할 때 자동으로 다운로드할 리소스팩의 URL을 입력합니다.
#   비워두면 서버의 server.properties에 설정된 리소스팩을 사용하거나,
#   자동 다운로드 기능을 비활성화합니다.
#   예시: "https://your-server.com/resourcepacks/craftedgear_rp.zip"
resource_pack_url: ""

# resource_pack_hash:
#   리소스팩 URL이 변경되지 않았더라도, 리소스팩 내용이 업데이트되었을 때
#   플레이어가 강제로 리소스팩을 다시 다운로드하게 하는 데 사용됩니다.
#   이 값을 변경하면 플레이어에게 업데이트된 리소스팩을 요청합니다.
#   예시: "691459a9307f82701b54c8d50b4f0b2f8a50630b" (이 값은 임의의 해시값입니다)
resource_pack_hash: ""

# General Settings:
# -----------------
# message_prefix:
#   플러그인 메시지 앞에 붙는 접두사입니다. 색상 코드를 사용할 수 있습니다.
message_prefix: "§8[§aCraftedGear§8] §r"

# Item Settings:
# ---------------
# default_item_lore_color:
#   커스텀 아이템의 기본 로어(설명) 색상입니다.
default_item_lore_color: "§7"